### ISSUE TITLE
Accelerator

### ISSUE THREAD

**Issue by Drob84761** [KennthShang/PhaBOX#34]
When using PhaTYP I am getting an issue with accelerator that I am not figuring out.

Running program: PhaTYP (Lifestyle prediction)
[1/7] filtering the length of contigs...
[2/7] calling genes with prodigal...
[3/7] running all-against-all alignment...
[4/7] converting sequences to sentences for language model...
[5/7] Predicting the lifestyle...
running with cpu
Map: 100%|██████████| 9898/9898 [00:00<00:00, 25994.96 examples/s]
Traceback (most recent call last):
  File "/90daydata/mmicrobe/David.Robinson/phabox/phabox2/bin/phabox2", line 8, in <module>
    sys.exit(main())
  File "/90daydata/mmicrobe/David.Robinson/phabox/phabox2/lib/python3.10/site-packages/phabox2/phabox2.py", line 388, in main
    phatyp.run(inputs)
  File "/90daydata/mmicrobe/David.Robinson/phabox/phabox2/lib/python3.10/site-packages/phabox2/phatyp.py", line 165, in run
    trainer, tokenized_data = init_bert(rootpth, midfolder, parampth)
  File "/90daydata/mmicrobe/David.Robinson/phabox/phabox2/lib/python3.10/site-packages/phabox2/scripts/ulity.py", line 219, in init_bert
    trainer = Trainer(
  File "/90daydata/mmicrobe/David.Robinson/phabox/phabox2/lib/python3.10/site-packages/transformers/trainer.py", line 345, in __init__
    self.create_accelerator_and_postprocess()
  File "/90daydata/mmicrobe/David.Robinson/phabox/phabox2/lib/python3.10/site-packages/transformers/trainer.py", line 3897, in create_accelerator_a
nd_postprocess
    self.accelerator = Accelerator(
TypeError: Accelerator.__init__() got an unexpected keyword argument 'dispatch_batches'

**Comment by Drob84761** [comment]
It appears that I had an install issue. Seems to have made it past that step. Thank you
